import Link from "next/link";

export default function Navbar() {
    return (
        <nav
            className="
sticky
top-0
z-50
bg-white/90
backdrop-blur-xl
border-b
border-[#EBEBEB]
"
        >
            <div
                className="
max-w-7xl
mx-auto
px-6
h-20
flex
items-center
justify-between
"
            >
                {/* Brand */}

                <Link
                    href="/salaries"
                    className="
flex
items-center
gap-3
group
"
                >
                    <div
                        className="
w-10
h-10
rounded-lg
bg-[#FF5A5F]
flex
items-center
justify-center
text-white
font-bold
shadow-sm
group-hover:scale-105
transition
"
                    >
                        T
                    </div>

                    <div>
                        <h1
                            className="
text-xl
font-bold
tracking-tight
text-[#222222]
"
                        >
                            TalentDash
                        </h1>

                        <p
                            className="
text-xs
text-[#717171]
"
                        >
                            Salary Intelligence
                        </p>
                    </div>
                </Link>

                {/* Navigation */}

                <div
                    className="
hidden
md:flex
items-center
gap-1
bg-[#F7F7F7]
rounded-full
p-1
border
border-[#EBEBEB]
"
                >
                    <Link
                        href="/salaries"
                        className="
px-5
py-2
rounded-full
text-sm
font-semibold
text-[#484848]
hover:bg-white
hover:text-[#FF5A5F]
hover:shadow-sm
transition
"
                    >
                        Salaries
                    </Link>

                    <Link
                        href="/companies"
                        className="
px-5
py-2
rounded-full
text-sm
font-semibold
text-[#484848]
hover:bg-white
hover:text-[#FF5A5F]
hover:shadow-sm
transition
"
                    >
                        Companies
                    </Link>

                    <Link
                        href="/compare"
                        className="
px-5
py-2
rounded-full
text-sm
font-semibold
text-[#484848]
hover:bg-white
hover:text-[#FF5A5F]
hover:shadow-sm
transition
"
                    >
                        Compare
                    </Link>
                </div>
            </div>
        </nav>
    );
}